# True or False. Used in a lot of comparison and logical operations in Python
print("-------------------------------------------------------")
bool(True)
bool(False)
print(bool(True))
print(bool(False))
print("-------------------------------------------------------")
# all the below evaluate to False. Everything else will evaluate to True in Python.
print("All the below evaluate to False. Everything else will evaluate to True in Python.")
print(bool(None))
print(bool(False))
print(bool(0))
print(bool(0.0))
print(bool([]))
print(bool({}))
print(bool(()))
print(bool(''))
print(bool(range(0)))
print(bool(set()))
# See Logical Operators and Comparison Operators section for more on booleans.
print("-------------------------------------------------------")
